### PR TITLE
better segment hovering when mouse is on node

### LINKED ISSUE #594: The Show error dialog panel can enter a vicious circle
see this https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/pull/538#issuecomment-552160224

Summary of the problem:
steps to reproduce:
A: user clicks on a wrong segment.
B: error panel is displayed.
C: user presses OK
D: the user click from step C is captured by the TM tool. However the `HoveredSegmentID` is not updated. This brings us back to step B.

### LINKED ISSUE #616: lane arrow tool may selects wrong node when holding ctrol
In the picture bellow with lane arrow tool the wrong node is hovered(note that the cursor is on the other end of the segment).
Cities_umOPGWgfr6
This happens whenever there is a one way road. 
this problem was introduced in the half overlay PR: #564

### PR DESCRIPTION
**Pull request by kianzarrin**
fixes #538
I have explained the math behind my approach in https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/576#issuecomment-559347611 . Please read it.
as suggested by @aubergine10 in https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/576#issuecomment-559659866 I provided option to "buff the clickability of segments based on their length". The option can be configured at compile time.

fixes #594
To fix this: when mouse ray is not valid I set `HoveredSegmentId` and `HoveredSegmentId` to zero

EDIT: fixes #616
I added an exception for when control key is down.

### CODE REVIEW

File: TLM/TLM/UI/TrafficManagerTool.cs [hunk 1]
```diff
@@ -939,12 +939,56 @@ public class TrafficManagerTool
                     }
                 }
 
-                return HoveredNodeId != 0 || HoveredSegmentId != 0;
+                if (HoveredNodeId != 0) {
```
Comment (kianzarrin) [inline TLM/TLM/UI/TrafficManagerTool.cs]: Argument can be made that his should be done at line 877 when we determine HoveredNodeID. That approach works for all cases except for level crossings. I found no way to get the following function to find level crossing nodes:
```RayCast(segmentInput, out RaycastOutput segmentOutput) ```
Therefore I decided to call `GetHoveredSegmentFromNode()` here.

The code can take multiple paths. the most complicated one is this:
1. We determine the `HoveredSegmentID`.
2. We determine `HoveredNodeID` by calculating shortest distance to the segment start or end node.
3. We fix `HoveredSegmentID` again by finding the segment which makes the minimum angle with the mouse-to-node vector.

it may sound confusing but thats the only way to support level crossings.

File: TLM/TLM/UI/TrafficManagerTool.cs [hunk 2]
```diff
@@ -939,12 +939,56 @@ public class TrafficManagerTool
...
 
-            return false; // mouseRayValid=false here
+            return HoveredNodeId != 0 || HoveredSegmentId != 0;
         }
 
+        /// <summary>
+        /// returns the node segment that is closest to the mouse pointer based on angle.
+        /// </summary>
+        internal ushort GetHoveredSegmentFromNode() {
+            bool considerSegmentLenght = true;
```
Comment (kianzarrin) [inline TLM/TLM/UI/TrafficManagerTool.cs]: Is there a better place for this hard coded configuration option?

**Comment by kianzarrin** [comment]
I tested this with bridges, tunnels, metro, level crossings, and of course normal junctions.

File: TLM/TLM/UI/SubTools/LaneArrowTool.cs [hunk 3]
```diff
@@ -143,6 +143,11 @@ public LaneArrowTool(TrafficManagerTool mainTool)
 
         protected override ushort HoveredNodeId {
         get {
+                bool ctrlDown = Input.GetKey(KeyCode.LeftControl) || Input.GetKey(KeyCode.RightControl);
```
Comment (kianzarrin) [inline TLM/TLM/UI/SubTools/LaneArrowTool.cs]: This fixes #616

File: TLM/TLM/UI/TrafficManagerTool.cs (hunk 2 above)
Comment (kvakvs) [reply TLM/TLM/UI/TrafficManagerTool.cs]: a constant somewhere in the same a class, or `Constants.cs` module (we have one or a few)

File: TLM/TLM/UI/TrafficManagerTool.cs [hunk 4]
```diff
@@ -939,12 +939,56 @@ public class TrafficManagerTool
...
+                });
+            return minSegId;
+        }
+
+        /// <summary>
+        /// returns the angle between v1 and v2.
+        /// input order does not matter.
+        /// The return value is between 0 to 180.
+        /// </summary>
+        private static float GetAgnele(Vector3 v1, Vector3 v2) {
```
Comment (kvakvs) [inline TLM/TLM/UI/TrafficManagerTool.cs]: Naming: `GetAngle`

File: TLM/TLM/UI/TrafficManagerTool.cs (hunk 2 above)
Comment (kianzarrin) [reply TLM/TLM/UI/TrafficManagerTool.cs]: thanks
