### PR TITLE
Half overlay

### LINKED ISSUE #548: Lane arrow tool: Alt+click only updates half segment
I have this road (just thrown together for testing):

image

The section of road in middle (highlighted above with Move It mod) is a single segment.

I open lane arrow tool and Alt+Click the segment in middle which gives this:

image

It's only updated one end of the segment (on the right). I was expecting it to update both ends?

If I Alt+Click a second time, it updates the other end:

image

### LINKED ISSUE #555: DrawNodeCircle has bug/redundancy. but it works.
TrafficManagerTool.DrawNodeCircle has a bug. but the bug is in redundant code so it works.
```
//the debug logs does not exist in original code
public void DrawNodeCircle(RenderManager.CameraInfo cameraInfo,
                            ushort nodeId,
                            Color color,
                            bool alpha = false) {
    NetNode[] nodesBuffer = Singleton<NetManager>.instance.m_nodes.m_buffer;
    Debug.Log($"m_segment0={nodesBuffer[nodeId].m_segment0}"); 
    NetSegment segment =
        Singleton<NetManager>.instance.m_segments.m_buffer[ nodesBuffer[nodeId].m_segment0];//BUG!!!!!!!!!!!
    Debug.Log($"vectors = {segment.m_startDirection} {segment.m_endDirection}");

    Vector3 pos = nodesBuffer[nodeId].m_position;
    float terrainY = Singleton<TerrainManager>.instance.SampleDetailHeightSmooth(pos);
    if (terrainY > pos.y) {
        pos.y = terrainY;
    }

    Bezier3 bezier;
    bezier.a = pos;
    bezier.d = pos;

////Redundant!!!!!!  instead: *** bezier.a=bezier.b=bezier.c=bezier.d=pos ***
    NetSegment.CalculateMiddlePoints(
        bezier.a,
        segment.m_startDirection,
        bezier.d,
        segment.m_endDirection, 
        false,
        false,
        out bezier.b,
        out bezier.c);

    Debug.Log($"bezier = {bezier.a} {bezier.b} {bezier.c} {bezier.d}");


    DrawOverlayBezier(cameraInfo, bezier, color, alpha);
}
```

m_segment0 in the code above can be zero (screenshot 1). this is similar to #549.
Fortunately here the code that utilizes m_segment0 is redundant at least to the best of my knowledge. In screenshot 2 m_segment0 is 0 and its directional vectors are subsequently zero as well. Nevertheless the final bezier result is accurate. screenshot 3 shows a valid m_segment0 will result in the same bezier result as invalid m_segment0.

Screenshot (46)
Screenshot (71)
Screenshot (70)

The call to CalculateMiddlePoints()

Why are we calling CalculateMiddlePoints on a single node anyway. node cannot collide with node? 

Risk
---
 - If CalculateMiddlePoints is really redundant then we are getting away with the bug because the bug is in redundant part of the code. In future skylines upgrades this might result in null reference exceptions.
 - If I am missing something and there are circumstances in which  CalculateMiddlePoints() is not redundant then we have a real bug.

Action
-----
we do not need `segment` or a call to `CalculateMiddlePoints` (AFIK). Instead ~~bezier.a=bezier.b=bezier.c=bezier.d=pos because its a simple node.~~
` DrawOverlayCircle(cameraInfo, color, pos, 20, alpha);`

### PR DESCRIPTION
**Pull request by kianzarrin**
fixes #548 :
When hovering over a segment with the lane arrow tool only half of the segment is highlighted letting the user know which half is being modified.

fixes #555: I took the opportunity to fix this related issue. 
I Removed buggy/redundant/weird code .
node highlights have the average radius of all connected segments see https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/555#issuecomment-557764120

EDIT by aubergine: Just adding image of the 'half overlay' so reviewers know what to look for:

image

EDIT: fixed a bug regarding  Alt+Click on a (LHT / RHD) map (see ,https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/pull/564#issuecomment-557771623)

### CODE REVIEW

**Comment by aubergine10** [comment]
Found one small issue (with normal lane arrow tool selected):

image

That half of the segment does not contain any outgoing lanes (it's the 'incoming end' of a one way road).

While clicking has no effect, it would be better if the overlay was not displayed when the segment half has no outgoing lanes (ie. tool not applicable).

**Comment by kianzarrin** [comment]
> Found one small issue (with normal lane arrow tool selected):
> While clicking has no effect, it would be better if the overlay was not displayed when the segment half has no outgoing lanes (ie. tool not applicable).
> Edit: Alternatively, it could show red 'half overlay' instead of the usual blue color. Not sure which would be best approach (if tool not applicable: no overlay, or different color)?

Wow great observation! This was already the problem without my half segment highlights. Its a Good idea to fix it as part of PR. 

I like the Idea of the red overlay too. currently I already use red for when segment selected and ALT is down in my previous commit. So I think I need to change that too.
```
if (altDown && HoveredSegmentId == SelectedSegmentId)
    color = MainTool.GetToolColor(true, true);
```

**Comment by aubergine10** [comment]
Looks _orange_ to me (when Alt is held down while hovering segment, or Ctrl is held down while hovering a node).

**Comment by aubergine10** [comment]
With this update I see only the highlighted half of the segment gets updated when Alt+Click which is much better.

I wonder if it would be worth adding that toggle feature I discussed in #548? So Alt+Click toggles the lane between _turning lane_ or _vanilla lane_ depending on it's current state.

**Comment by aubergine10** [comment]
Possible bug with Alt+Click: I'm on a left hand traffic (LHT / RHD) map, so this turning lane choice seems wrong (it would cut across oncoming traffic):

image

Although maybe I'm not understanding it correctly?

In UK, the dedicated turning lane is usually the one of the left, with the lane to the right going ahead+right. Here are some examples...

At a junction:

image

At a roundabout (where 'turning lane' means 'you must exit roundabout at next junction'):

image

We even cut up bus lanes to make room for turning lanes:

image

I suspect it may be different in other countries (ie. not purely dependent on the driving side). As such, a mod option may be beneficial at some point? (would have to think carefully how to word it)

**Comment by aubergine10** [comment]
Further to my comment above about which side should get the turning lane, I noticed that if there are three lanes to choose from vanilla automatically chooses these lane arrows:

image

And in that situation an Alt+Click does turn the left lane in to a turning lane (which seems correct):

image

(sorry, I know this is getting off topic of the PR, but thought I'd mention it just in case)

**Comment by aubergine10** [comment]
Maybe when holding `Alt` key, we should highlight the half-lane that will be affected (make it really obvious to use which lane will change), rather than the half-segment?

**Comment by kianzarrin** [comment]
>Maybe when holding Alt key, we should highlight the half-lane that will be affected (make it really obvious to use which lane will change), rather than the half-segment?

I am not sure if that is practical. The calculations that needs to be done in each game click will be too much (unless if i cache it I guess). In another PR maybe.

Mean while I have done this: 
Pictures below respectively:
hover
ALT hover
hover (or ALT hover) with no outgoing lanes
selected segment
selected segment + ALT hover

Screenshot (93)

Cities_ Skylines 23-Nov-19 8_58_04 AM
Cities_ Skylines 23-Nov-19 8_57_13 AM

Screenshot (94)

Cities_ Skylines 23-Nov-19 8_58_15 AM

hmmm. I am going to change the color of alt hover to be strong blue and different from selected segment.

**Comment by kianzarrin** [comment]
I ended up changing the alpha:
hover:
Screenshot (93)


ALT hover:
Cities_ Skylines 23-Nov-19 9_21_57 AM

**Comment by kianzarrin** [comment]
@aubergine10 Sorry I missed some of your messages
>Looks orange to me (when Alt is held down while hovering segment, or Ctrl is held down while hovering a node).

Not any more. I already fix this.

>I wonder if it would be worth adding that toggle feature I discussed in #548? So Alt+Click toggles the lane between turning lane or vanilla lane depending on it's current state.

>I suspect it may be different in other countries (ie. not purely dependent on the driving side). As such, a mod option may be beneficial at some point? (would have to think carefully how to word it)

In the last PR we talked about state machine. I created #567 to address it.

>Possible bug with Alt+Click: I'm on a left hand traffic (LHT / RHD) map, so this turning lane choice seems wrong (it would cut across oncoming traffic):

Nice catch! that is a bug. I think its more fitting to fix it in #567

**Comment by aubergine10** [comment]
> Damn it I have been using LHD in my code to refer to British roads

I regularly make similar mistake, confusing the four terms: LHT, RHD, vs. RHT, LHD

See my comment in #567 regarding 'nearside' and 'farside' terminology which is driving direction agnostic.

**Comment by kianzarrin** [comment]
After playing around with the highlights I can still spot some caveats. Please put this review on halt until I fix them. I will continue the discussion about colors and other stuff in #548.
So far I have the following problems:
- I want to improve the colors again 
- Hovering highlights half segment but selection highlights the hole thing. this is inconsistent.
- null exception occures when I select one segment but ALT-hover over another.
- The length of the highlighted segment is not always half the segment, this can confuse the user because when he hovers the mouse over the would-be highlighted area of the segment, the highlight does not come up.

**Comment by aubergine10** [comment]
> null exception occurs when I select one segment but ALT-hover over another (possibly #563).

I'm not sure it is as user is reporting the exception when save loads or, if not then, when saving a game. Also, we've had similar error reported (see #566) for TM:PE STABLE v10.20 which doesn't even contain these features. I suspect something in base game or steam common distro has changed which is triggering some of the errors reported.

That being said, good catch on the null exception when hovering other half of selected segment!

**Comment by kianzarrin** [comment]
@kvakvs @aubergine10 @krzychu124 
I sorted out everything. My code should be perfect :)
I am ready for the next round of review.

File: TLM/TLM/UI/TrafficManagerTool.cs [hunk 1]
```diff
@@ -415,50 +415,81 @@ public class TrafficManagerTool
             DrawNodeCircle(cameraInfo, nodeId, GetToolColor(warning, false), alpha);
         }
 
+        /// <returns>the average half width of all connected segments</returns>
+        private float NodeRadius(ushort nodeId) {
```
Comment (kvakvs) [inline TLM/TLM/UI/TrafficManagerTool.cs]: General idea function names should begin with a verb to denote an action done, i.e. GetNodeRadius(), while variables or properties can remain as nouns.

**Comment by kvakvs** [comment]
Note how quickly features get Alt, Shift etc modifiers. We must quickly come with a solution for UX, users will forget these keys or never know they exist.

File: TLM/TLM/UI/SubTools/LaneArrowTool.cs [hunk 2]
```diff
@@ -132,27 +185,21 @@ public LaneArrowTool(TrafficManagerTool mainTool)
                 if (((netManager.m_segments.m_buffer[HoveredSegmentId].m_startNode == HoveredNodeId)
                      || (netManager.m_segments.m_buffer[HoveredSegmentId].m_endNode == HoveredNodeId))
                     && ((nodeFlags & NetNode.Flags.Junction) != NetNode.Flags.None))
-                {
-                    NetTool.RenderOverlay(
-                        cameraInfo,
-                        ref Singleton<NetManager>.instance.m_segments.m_buffer[HoveredSegmentId],
-                        MainTool.GetToolColor(altDown, false),
-                        MainTool.GetToolColor(altDown, false));
+                    {
```
Comment (kvakvs) [inline TLM/TLM/UI/SubTools/LaneArrowTool.cs]: indent here makes no sense, either unindent once, or join with the previous line.  I usually do this part manually, selecting the variant which reads better. The rest of the code is almost always auto-formatted (one block or one function at a time to keep it under control), for simplicity.

File: TLM/TLM/UI/TrafficManagerTool.cs [hunk 3]
```diff
@@ -415,50 +415,80 @@ public class TrafficManagerTool
...
+            float sum_half_width = 0;
+            int count = 0;
+            Constants.ServiceFactory.NetService.IterateNodeSegments(
+                nodeId,
+                (ushort segmentId, ref NetSegment segment) => {
+                    sum_half_width += segment.Info.m_halfWidth;
+                    count++;
+                    return true;
+                });
+            return sum_half_width / count;
```
Comment (kvakvs) [inline TLM/TLM/UI/TrafficManagerTool.cs]: I know it may look impossible, can there exist degenerate nodes with 0 segments? Let's check with @krzychu124 
In that case this division may crash.

File: TLM/TLM/UI/TrafficManagerTool.cs [hunk 4]
```diff
@@ -415,50 +415,80 @@ public class TrafficManagerTool
...
-            Vector3 pos = nodesBuffer[nodeId].m_position;
-            float terrainY = Singleton<TerrainManager>.instance.SampleDetailHeightSmooth(pos);
-            if (terrainY > pos.y) {
-                pos.y = terrainY;
+            float r = CalculateNodeRadius(nodeId);
+            Vector3 pos = Singleton<NetManager>.instance.m_nodes.m_buffer[nodeId].m_position;
+            DrawOverlayCircle(cameraInfo, color, pos, r * 2, alpha);
+        }
+
+        public void DrawCutSegmentEnd(RenderManager.CameraInfo cameraInfo,
```
Comment (kvakvs) [inline TLM/TLM/UI/TrafficManagerTool.cs]: New public function? Please document what it does.

File: TLM/TLM/UI/SubTools/LaneArrowTool.cs [hunk 5]
```diff
@@ -108,13 +109,65 @@ public LaneArrowTool(TrafficManagerTool mainTool)
             cursorInSecondaryPanel_ = windowRect3.Contains(Event.current.mousePosition);
         }
 
+
+        private bool IsHoverValid() => IsSegmentEndHoverable(HoveredSegmentId, HoveredNodeId);
+        private bool IsSegmentEndHoverable(ushort segmentId, ushort nodeId) {
```
Comment (kvakvs) [inline TLM/TLM/UI/SubTools/LaneArrowTool.cs]: Add an one-line explanation what this function does

File: TLM/TLM/UI/SubTools/LaneArrowTool.cs [hunk 6]
```diff
@@ -108,13 +109,65 @@ public LaneArrowTool(TrafficManagerTool mainTool)
...
+            NetNode[] nodesBuffer = Singleton<NetManager>.instance.m_nodes.m_buffer;
+            bool IsJunction(ushort nodeId) => (nodesBuffer[nodeId].m_flags & NetNode.Flags.Junction) != 0;
+
+            // Outgoing lanes toward the node is incomming lanes to the segment end.
+            return IsJunction(nodeId) && segEnd.incoming;
+        }
+
+        protected override ushort HoveredNodeId {
+        get {
+                if (!IsSegmentEndHoverable(HoveredSegmentId, base.HoveredNodeId))
```
Comment (kvakvs) [inline TLM/TLM/UI/SubTools/LaneArrowTool.cs]: Please add a 2 line explanation what is happening here.

File: TLM/TLM/UI/SubTools/LaneArrowTool.cs [hunk 7]
```diff
@@ -108,13 +109,65 @@ public LaneArrowTool(TrafficManagerTool mainTool)
...
+                    if (IsSegmentEndHoverable(HoveredSegmentId, otherNodeId)) {
+                        return otherNodeId;
+                    }
+                }
+                return base.HoveredNodeId;
+            }
+            set => base.HoveredNodeId = value;
+        }
+
+        private void DrawSegmentEnd(
```
Comment (kvakvs) [inline TLM/TLM/UI/SubTools/LaneArrowTool.cs]: Add an one-line explanation what this function does

File: TLM/TLM/UI/TrafficManagerTool.cs (hunk 3 above)
Comment (aubergine10) [reply TLM/TLM/UI/TrafficManagerTool.cs]: Good catch. There has definitely been a problem in the past with "phantom nodes" (nodes which have no segments).

Most notably, the Move It mod has this button:

image

Comment (kianzarrin) [reply TLM/TLM/UI/TrafficManagerTool.cs]: The code on  laneArrowTool.cs:115 will prevent that:
```c#
           if(nodeId == 0 || segmentId == 0) {
                return false;
            }
```

Comment (aubergine10) [reply TLM/TLM/UI/TrafficManagerTool.cs]: If that's the case then please add to the code comment for `CalculateNodeRadius()` a note about needing to check there are segments present before calling the function.

Comment (kianzarrin) [reply TLM/TLM/UI/TrafficManagerTool.cs]: I will add check for segmentId==0 just in case.

File: TLM/TLM/UI/SubTools/LaneArrowTool.cs [hunk 8]
```diff
@@ -108,13 +109,65 @@ public LaneArrowTool(TrafficManagerTool mainTool)
...
+#if DEBUG
+            if(!Constants.ServiceFactory.NetService.IsNodeValid(nodeId) ||
+               !Constants.ServiceFactory.NetService.IsSegmentValid(segmentId)) {
+                Debug.LogError("Invalid node or segment ID");
+            }
+#endif
+            ExtSegmentEndManager segEndMan = ExtSegmentEndManager.Instance;
+            ExtSegmentEnd segEnd = segEndMan.ExtSegmentEnds[segEndMan.GetIndex(segmentId, nodeId)];
+            NetNode[] nodesBuffer = Singleton<NetManager>.instance.m_nodes.m_buffer;
+            bool IsJunction(ushort nodeId) => (nodesBuffer[nodeId].m_flags & NetNode.Flags.Junction) != 0;
```
Comment (krzychu124) [inline TLM/TLM/UI/SubTools/LaneArrowTool.cs]: Why have you created local function if you can calculate bool value straight ahead??
Why argument name of your local function is overlapping with method argument name?

File: TLM/TLM/UI/TrafficManagerTool.cs (hunk 3 above)
Comment (krzychu124) [reply TLM/TLM/UI/TrafficManagerTool.cs]: > The code on laneArrowTool.cs:115 will prevent that

Of course it will prevent that, but it clearly means that it won't even call your delegate to increment `count` variable 😉

File: TLM/TLM/UI/TrafficManagerTool.cs [hunk 9]
```diff
@@ -415,50 +415,80 @@ public class TrafficManagerTool
...
+                       float cut,
+                       bool bStartNode,
+                       Color color,
+                       bool alpha = false) {
+            ref NetSegment segment = ref Singleton<NetManager>.instance.m_segments.m_buffer[segmentId];
+            float width = segment.Info.m_halfWidth;
+            ushort nodeId, otherNodeId;
+
+            NetNode[] nodeBuffer = Singleton<NetManager>.instance.m_nodes.m_buffer;
+            Vector3 GetPos(ushort nodeId) {
```
Comment (krzychu124) [inline TLM/TLM/UI/TrafficManagerTool.cs]: I think it would be better to move that function outside this method.

File: TLM/TLM/UI/TrafficManagerTool.cs [hunk 10]
```diff
@@ -415,50 +415,80 @@ public class TrafficManagerTool
...
+                Vector3 pos = nodeBuffer[nodeId].m_position;
+                float terrainY = Singleton<TerrainManager>.instance.SampleDetailHeightSmooth(pos);
+                if (terrainY > pos.y) {
+                    pos.y = terrainY;
+                }
+                return pos;
             }
 
+            bool IsMiddle(ushort nodeId) => (nodeBuffer[nodeId].m_flags & NetNode.Flags.Middle) != 0;
```
Comment (krzychu124) [inline TLM/TLM/UI/TrafficManagerTool.cs]: Overlapping argument name again.

**Comment by krzychu124** [comment]
A bit weird segment highlight when outgoing segment is too short, but other than that works good.

half-segment

**Comment by aubergine10** [comment]
> A bit weird segment highlight when outgoing segment is too short, but other than that works good.

Whenever a segment has lane arrows at both ends, only one half of it will get highlighted so the user can see which end of segment is being altered if they click.

If the segment only has arrows at one end, then whole segment is highlighted (it doesn't matter which end you click on). This was done to make it easier to click on short segments when they only have arrows at one end.

**Comment by krzychu124** [comment]
@aubergine10  Yes, I know, but it still looks weird. 
When I'm hovering over some node, I'm wiling to change arrows of incoming lanes to this node, not somewhere else.
Maybe I'm too meticulous, but I see inconsistency there, because both segments are outgoing. First on the right is highlighting on red(OK, there are no lane arrows at both ends) but the other is fully highlighted blue when it shouldn't be highlighted at all near that node in my opinion.

**Comment by aubergine10** [comment]
Ah, I see - the other end of that short node in your GIF doesn't actually have lane arrows, despite being "junction node", because it's 1-way street. Good catch!

**Comment by krzychu124** [comment]
Yes, both segments are 1-way streets, but different hover behavior, which might annoy user and provoke missclicks - you can't click on red highlighted segment (OK) but on that weird blue, sure, then lane arrows window will show up near the other node.

**Comment by kianzarrin** [comment]
@krzychu124
> Yes, both segments are 1-way streets, but different hover behavior, which might annoy user and provoke missclicks - you can't click on red highlighted segment (OK) but on that weird blue, sure, then lane arrows window will show up near the other node.

Good catch. I will fix it. :)

**Comment by aubergine10** [comment]
Would it be worth removing the red highlight also?

For color vision impaired users, distinguishing between red and blue might be difficult (I'd have to read through my notes on #287 to check).

Maybe instead of red highlight, just don't highlight at all. That way it's simple UX: If it highlights, you can click it to do something, otherwise it's not relevant to the selected tool.

**Comment by kianzarrin** [comment]
@aubergine10 

> For color vision impaired users, distinguishing between red and blue might be difficult (I'd have to read through my notes on #287 to check).

Good idea! Makes my job easier too :) . In any case I will fix the problem @krzychu124  raised because fixing it also makes my code shorter.

One more case. What if we have a junction with one way out. changing lane arrows don't make any sense as there is only one direction to go to. So maybe we shouldn't highlight it?

I don't know how to take U turn into consideration. 

That said it is possible to have lane arrows toward wrong direction for example : 
 step 1- manually override lane arrows to go to a road. 
 step 2- delete that road.
Screenshot (125)

in such circumstances you can use lane arrow tool to fix the arrows. 

It would be nice if we could automatically remove lane arrows toward lane direction. Also we should not allow the user to put lane arrows toward wrong directions.

So talking all that into consideration do you think I should allow selection of cases where there is only one way out?

**Comment by aubergine10** [comment]
> One more case. What if we have a junction with one way out. changing lane arrows don't make any sense as there is only one direction to go to. So maybe we shouldn't highlight it?

Agreed. Possibly related issues: #344

> I don't know how to take U turn into consideration.

U-turns are a mess at the moment, there's like 2 or 3 ways to do them (off the top of my head: Lane connectors, and junction restrictions). We should only have one way to implement u-turns. I think there's already some issues tracking that. Possibly related issues: #364, #347, #365, #293

> That said it is possible to have lane arrows toward wrong direction for example :

Yup, this is a general problem with all the tools. We need to have a think as to how to handle that situation better and, in particular, make sure the user realises their road changes just screwed up their customisations.  Possibly related issues: #368, #457, #43

Will test this PR again later this evening if time permits.

**Comment by aubergine10** [comment]
Should train tracks be excluded? They have no visible lane arrows so any changes made would be invisible to user, which would result in difficult to diagnose problems with rail routing. I suspect this is more general issue with the lane arrows tool.

image

Same with tram tracks:

image

And monorail:

image

And metro:

image

There's some flags (#513 for example) that indicates what vehicles can use the network, so you could filter to just those that allow cars?

**Comment by aubergine10** [comment]
Regarding that stuff above about filtering out non-car networks, that could be a separate PR if desired as it's general issue of the lane arrow tool and not specific to the work you've been doing.

The remaining comments from @krzychu124 are more important for this PR.

**Comment by kianzarrin** [comment]
@aubergine10 
> The remaining comments from @krzychu124 are more important for this PR.

Yes that one is fixed already.

> Regarding that stuff above about filtering out non-car networks, that could be a separate PR if desired as it's general issue of the lane arrow tool and not specific to the work you've been doing.

Good idea. This PR is already growing out of control. Created #585.

If there are no bugs in this code lets merge this in before the code gets out of date.

File: TLM/TLM/UI/SubTools/LaneArrowTool.cs (hunk 8 above)
Comment (kianzarrin) [reply TLM/TLM/UI/SubTools/LaneArrowTool.cs]: Forgot to remove IsJunction. Ill do it now.

File: TLM/TLM/UI/TrafficManagerTool.cs (hunk 10 above)
Comment (kianzarrin) [reply TLM/TLM/UI/TrafficManagerTool.cs]: No not this time.

**Comment by kianzarrin** [comment]
I am ready for the next round of this PR

File: TLM/TLM/UI/TrafficManagerTool.cs (hunk 10 above)
Comment (krzychu124) [reply TLM/TLM/UI/TrafficManagerTool.cs]: Of course that name is overlapping. Look at line 450 😉  (BTW, I have no idea where you use these variables, because I couldn't find any reference)

Comment (kianzarrin) [reply TLM/TLM/UI/TrafficManagerTool.cs]: Oh yes. I need to delete unused variables.
