### PR TITLE
IterateNodeSegments sometimes does not work. Fixes #549

### LINKED ISSUE #549: IterateNodeSegments sometimes does not work
sometimes when you call IterateNodeSegments() with clock direction, it may not iterate through any segments. That happens if 
`node.m_segment0 == 0`.
Screenshot (46)

to create this condition you should create a junction and then bulldoze m_segment0 of the node of the junction (first segment).

the code responsible is [here](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/blob/faae760f5d6cd7ceae88e9d35adc70ae3abd5b2e/TLM/TMPE.CitiesGameBridge/Service/NetService.cs#L123):
```ushort segmentId = node.GetSegment(0);```

This is the fix:
```ushort segmentId = 0;
for (int i = 0; i < 8; ++i) {
    segmentId = node.GetSegment(i);
    if (segmentId != 0) {
        break;
    }
}
ushort initSegId = segmentId;
```

Ill create a pull request soon.

### PR DESCRIPTION
**Pull request by kianzarrin**
Fixes #549 . See the issue for full dets.
I tested this and it works. Here is how I tested it:
This bug was breaking my roundabout detection. With this patch my roundabout detection works again.

### CODE REVIEW

File: TLM/TMPE.CitiesGameBridge/Service/NetService.cs [hunk 1]
```diff
@@ -121,6 +121,12 @@ public class NetService : INetService {
                     }
                 } else {
                     ushort segmentId = node.GetSegment(0);
+                    for (int i = 0; i < 8; ++i) {
+                        segmentId = node.GetSegment(i);
+                        if (segmentId != 0) {
+                            break;
+                        }
+                    }
```
Comment (kvakvs) [inline TLM/TMPE.CitiesGameBridge/Service/NetService.cs]: Remove the initial variable initialization. Just `ushort segmentId`.
Also handle the situation when all `segmentId`s in the node are 0 (in that case `segmentId` will also be 0). Could be a highly improbable case but what do i know about how the game works?
