### PR TITLE
Game language detection fix - modded language

### LINKED ISSUE #533: Cannot normally get using game language in 11.0 Third-party local translation.
### In 11.0 alpha version, TM:PE Cannot normally get using game language in using Third-party local translation mods.
(e.g.: https://steamcommunity.com/sharedfiles/filedetails/?id=812789818)

**But can normally in STABLE(10.20) and LABS(10.21.1).**

### Screenshots:

In STABLE(10.20):

In LABS(10.21.1):

In Alpha(11.0):

**Also, please review my Simplified Chinese in Crowdin. Because some translation is not correct in 11.0 version.**

### PR DESCRIPTION
**Pull request by krzychu124**
Fixes #533 
- fixed detection of game language when user is using 3rd party language mod

### CODE REVIEW

File: TLM/TLM/UI/Localization/Translation.cs [hunk 1]
```diff
@@ -189,11 +169,32 @@ public class Translation {
             return filename;
         }
 
+        private static string FixLanguageNameIfLanguageMod(string language) {
```
Comment (aubergine10) [inline TLM/TLM/UI/Localization/Translation.cs]: Would it be better called `GetValidLanguageCode`?

Also, check to see if `language` is recognised first and if so just return it, otherwise do the `switch` to fix known weird language codes with a `default` of `en`?

Comment (aubergine10) [reply TLM/TLM/UI/Localization/Translation.cs]: Edited comment above.

Comment (krzychu124) [reply TLM/TLM/UI/Localization/Translation.cs]: I'm not so good at naming methods 😄 
I will refactor this to cover these cases.
